### PR TITLE
Merged Android version

### PR DESCRIPTION
**Pull request by cosmarc**
Merged Android version based on https://github.com/andreluisjunqueira/react-native-documentscanner-android, also added base64 support for android and many fixes.

### CODE REVIEW

**Comment by Michaelvilleneuve** [comment]
Hi @cosmarc ! Well done ! Could you provide screenshots showing it functional please ?

**Comment by cosmarc** [comment]
It's actually @estuardoeg's work, but he didn't created a PR. Yes, I'll come up with them asap.

**Comment by cosmarc** [comment]
Android:
android

iOS:
ios

**Comment by Michaelvilleneuve** [comment]
Hi @cosmarc I have been trying the android version this morning. I have some issues with it, I'm trying to figure out what is wrong, in short : 
- Not as efficient as the ios version
- Does not recognize small documents (credit cards, etc)
- the overlay color does not seem to be working 
- in general, code seems hacky, lots of useless code and comments

I would love to finish it with your help :)

**Pull request closed without merging**
