### PR TITLE
Added possibility to stop camera manually.

### PR DESCRIPTION
**Pull request by tskorupka**

### CODE REVIEW

**Comment by Michaelvilleneuve** [comment]
Hi, thank you for your work. 

I'm not sure why we would need that.
Removing the component from the virtual dom is enough for me.

And I'm not sure that an imperative API would be the best option here, maybe a boolean props that would activate and deactivate the camera.

**Comment by tskorupka** [comment]
Even if component is removed from virtual dom it is not stopping the background task which is detecting if it can take photo and it does it. So I just make a function public.

**Comment by Michaelvilleneuve** [comment]
@tskorupka Ok I get it, maybe we could put it the componentWillUnMount function so it is automatically done ?

**Comment by tskorupka** [comment]
I will read more about how componentWillUnMount works and change actual solution.

**Comment by WeslleyNasRocha** [comment]
i actually did this on another pull request #46

**Pull request closed without merging**
