### PR TITLE
Add basic android support

### PR DESCRIPTION
**Pull request by Michaelvilleneuve**
Following up on https://github.com/Michaelvilleneuve/react-native-document-scanner/pull/47 cosmarc's work, a new and working android branch

What has been done : 

- [x] Document detection
- [x] Image cropping
- [x] Returning rectangle coordinates

What's left to do : 

- [x] Dynamic overlay color
- [ ] Base64 support

### CODE REVIEW

**Comment by Frekansapp** [comment]
Hi @Michaelvilleneuve, thank you for doing this. It's much more efficent than #47 detection of document is faster but must be in opposite colors to recognize document, like white paper on black background. Do you have any chance to improve this behaviour?

**Comment by Michaelvilleneuve** [comment]
hi @Frekansapp,
I have noticed the exact same problem, unfortunately I do not have much time left to work on it.
The problem is probably in the color processing of the document since OpenCV uses special treatment. I'll try to look into it ASAP but I can't promise any release date yet.

Aside from that, would you consider it stable enough on your end for an official release ?

**Comment by Frekansapp** [comment]
@Michaelvilleneuve i think it's stable enough for release. But i have noticed another small issue about camera angle. Recognize the document according to the angle of holding the phone. (like after 60 degrees) but the picture seems to be compressed from the edges.

**Comment by Arjanvanmaren** [comment]
Can this be merged?

**Comment by Michaelvilleneuve** [comment]
@Arjanvanmaren we have had a lot going on lately internally but we plan to release this branch in the next few days 👍

**Comment by GaetanB999** [comment]
Hello, 
will this branch be compatible with RN 0.60 and AndroidX ?

**Comment by Michaelvilleneuve** [comment]
@GaetanB999 No it is not, would love to accept a PR

**Pull request merged**
